version: "3.7"
services:
  database:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: app-skeleton
      POSTGRES_USER: root
      POSTGRES_DB: app-skeleton

  service:
    image: ${APP_IMAGE_TAG}
    entrypoint: bash -c
    init: true
    env_file: $ENVFILE
    volumes: [$VOLUMES]
    ports:
      - 9292:9292
    depends_on:
      - database
